import { NextResponse } from "next/server";
import { saveFullDiagnosis } from "../../../lib/saveReports";

export const runtime = "nodejs";
export const maxDuration = 60;

export async function POST(req: Request) {
  try {
    const body = await req.json().catch(() => ({}));

    const manuscript = body.manuscript || body.text || "";

    if (!manuscript || manuscript.trim().length === 0) {
      return NextResponse.json(
        { error: "No manuscript text was provided." },
        { status: 400 }
      );
    }

    const apiKey = process.env.ANTHROPIC_API_KEY;

    if (!apiKey) {
      return NextResponse.json(
        {
          error:
            "Missing ANTHROPIC_API_KEY. Check your .env.local file and your Vercel environment variables.",
        },
        { status: 500 }
      );
    }

    const systemPrompt = `
You are THE HOVEL EDITOR.

You produce a sharp, honest editorial diagnosis for literary manuscript excerpts.

Your job is not to flatter. Your job is to identify what is working, what is weakening the piece, where the voice is strongest, where the prose is over-explaining, and what the writer should do next.

Write in a direct, intelligent, human editorial voice.

Do not sound like generic AI feedback.
Do not give empty praise.
Do not use vague workshop language.
Do not rewrite the whole manuscript unless specifically asked.
Do not be cruel, but be honest.

Return the report in this structure:

# VOICE REPORT

## 1. Executive Voice Verdict
Give a clear overall verdict on the voice, authority, tone, and emotional power of the manuscript.

## 2. Voice Scorecard
Score these from 1 to 5 and briefly explain each:
- Distinctiveness
- Authority
- Emotional Control
- Image Discipline
- Sentence Rhythm
- Trust in the Reader

## 3. What Is Working
Identify the strongest elements.

## 4. What Is Weakening the Piece
Identify the main problems, especially repetition, over-explaining, tonal inflation, unclear movement, or places where the writing tries too hard.

## 5. Most Powerful Lines or Moments
Call out the best moments and explain why they work.

## 6. Lines or Moves That Need Attention
Identify weak spots, soft spots, overwriting, cliché, or places that should be cut or sharpened.

## 7. Surgical Revision Plan
Give a practical list of changes the writer should make next.

## 8. Final Editorial Verdict
End with a blunt but useful final assessment.
`;

    const response = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": apiKey,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: process.env.ANTHROPIC_MODEL || "claude-sonnet-4-5",
        max_tokens: 4000,
        temperature: 0.4,
        system: systemPrompt,
        messages: [
          {
            role: "user",
            content: `Run a Voice Report on this manuscript:\n\n${manuscript}`,
          },
        ],
      }),
    });

    const rawText = await response.text();

    let data: any = {};

    try {
      data = JSON.parse(rawText);
    } catch {
      return NextResponse.json(
        {
          error: "Anthropic returned a non-JSON response.",
          details: rawText,
        },
        { status: 500 }
      );
    }

    if (!response.ok) {
      return NextResponse.json(
        {
          error:
            data?.error?.message ||
            data?.message ||
            "Anthropic API request failed.",
          details:
            typeof data === "string" ? data : JSON.stringify(data, null, 2),
        },
        { status: response.status }
      );
    }

    const report =
      data?.content?.[0]?.text ||
      data?.content?.map((item: any) => item.text).join("\n\n") ||
      "";

    if (!report) {
      return NextResponse.json(
        {
          error: "The AI response came back empty.",
          details: JSON.stringify(data, null, 2),
        },
        { status: 500 }
      );
    }

    const placeholderReport =
      "Not generated by this Voice Report run. Reserved for future full 5 CORE diagnosis.";

    let submissionId: string | null = null;

    try {
      submissionId = await saveFullDiagnosis(manuscript, {
        voice: report,
        structure: placeholderReport,
        repetition: placeholderReport,
        market: placeholderReport,
        surgical: placeholderReport,
        roadmap: placeholderReport,
      });
    } catch (saveError: any) {
      const saveDetails =
        saveError?.message || "Unknown Supabase save error.";

      return NextResponse.json(
        {
          error: `The AI report generated, but saving to Supabase failed. ${saveDetails}`,
          details: saveDetails,
          report,
        },
        { status: 500 }
      );
    }

    return NextResponse.json({
      report,
      submissionId,
      saved: true,
    });
  } catch (err: any) {
    return NextResponse.json(
      {
        error: err?.message || "Unknown server error.",
      },
      { status: 500 }
    );
  }
}